Rolled up updates
Klahanie/klahanie pull request #93
Opened 2021-01-20 00:11 UTC by jhutchings1

👋🏻  @SharonManyara I went ahead and took all of your pull requests from the past few days and I retargeted them against this new branch called `rolled-up-updates` using this technique. This will let us review all of the changes together on staging before putting them out on the production site. You can do this too if you are working on something and accidentally send a PR to the default branch before it's ready. Here are some instructions for you :) https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/changing-the-base-branch-of-a-pull-request

2021-01-20 00:13 UTC, jhutchings1 commented
Also, it looks like your changes for the how to pay your dues document didn't have the same filename, so I'll have to go and change the link on that.

2021-01-20 00:33 UTC, jhutchings1 commented
@SharonManyara Do you mind clicking around the staging site to see if everything looks like you expect it to? https://klahanie.github.io/klahanie

2021-01-21 21:04 UTC, SharonManyara requested changes
@jhutchings1 
i just realized the application says 2020 instead of 2021. This is the updated file 
[Aquatics Lifeguard Employment Application 2021.pdf](https://github.com/Klahanie/klahanie/files/5852141/Aquatics.Lifeguard.Employment.Application.2021.pdf)

2021-01-22 02:00 UTC, jhutchings1 commented
@SharonManyara Do you want to switch to the rolled-up-updates branch and make the change by uploading the new file? Don't want to cut off a learning opportunity.

2021-02-02 17:39 UTC, SharonManyara commented on _amenities/pools/index.md
> +* [Lifeguard Employment Application]({{site.url}}/files/Aquatics Lifeguard Employment Application 2020.pdf)
[Aquatics Lifeguard Employment Application 2021.pdf](https://github.com/Klahanie/klahanie/files/5913117/Aquatics.Lifeguard.Employment.Application.2021.pdf)

2021-02-02 18:18 UTC, SharonManyara requested changes

2021-02-02 18:18 UTC, SharonManyara commented on _amenities/pools/index.md
> +* [Lifeguard Employment Application]({{site.url}}/files/Aquatics Lifeguard Employment Application 2020.pdf)
updating new file

2021-02-09 18:35 UTC, SharonManyara commented
@jhutchings1 how do i correct exit code 1?

2021-02-09 19:14 UTC, jhutchings1 commented on _amenities/pools/Lifeguard Employment Application
> +({{site.url}}/files/Aquatics Lifeguard Employment Application 2021.pdf)
This file shouldn't exist. Delete it?

2021-02-09 19:16 UTC, jhutchings1 commented
> @jhutchings1 how do i correct exit code 1?

This is your problem, the file you are linking to doesn't exist. Double check the name of the file and confirm that it's the same in both places. 
- ./_site/amenities/pools/index.html
  *  internally linking to /files/Aquatics Lifeguard Employment Application 2020.pdf, which does not exist (line 0)
     <a href="/files/Aquatics Lifeguard Employment Application 2020.pdf">Lifeguard Employment Application</a>

2021-02-15 16:53 UTC, sspicer1 approved these changes

2021-02-15 16:56 UTC, sspicer1 requested changes
looks like there is a conflict line 13-17

2021-02-16 18:21 UTC, SharonManyara requested changes
@sspicer1 i corrected line 13-17 (i hope). Please double check staging site (Thank you!)

2021-02-16 18:21 UTC, SharonManyara commented on _amenities/pools/index.md
> +* [Lifeguard Employment Application]({{site.url}}/files/Aquatics Lifeguard Employment Application 2020.pdf)
@sspicer1

2021-02-18 19:52 UTC, SharonManyara approved these changes

2021-02-18 19:52 UTC, sspicer1 approved these changes

2021-02-18 20:00 UTC, sspicer1 approved these changes

2021-02-19 01:08 UTC, jhutchings1 commented
I went ahead and cleared up the merge conflicts and fixed the broken links that were getting flagged in the tests. Merging.

2021-02-19 01:08 UTC, merged