Update swim-lessons.md
Klahanie/klahanie pull request #97
Opened 2021-02-09 17:15 UTC by ALFalls

Edits @sspicer1 @SharonManyara

2021-02-11 01:34 UTC, jhutchings1 commented
👋🏻  Hey @ALFalls Just an FYI that the staging site only keeps the most recent branch available for testing. If you'll be making many updates in a day, I recommend putting them all on a single branch and testing them together.

2021-02-11 01:39 UTC, jhutchings1 commented on _amenities/pools/swim-lessons.md
> +<strong>Quick Links</strong>
What are you trying to accomplish with this change? This moves the Quick links header out of the floating card on the right side of the page and puts it into the yellow alert banner.

2021-02-12 02:40 UTC, ALFalls commented
> 👋🏻 Hey @ALFalls Just an FYI that the staging site only keeps the most recent branch available for testing. If you'll be making many updates in a day, I recommend putting them all on a single branch and testing them together.

@jhutchings1 Sure. Can you please send instructions for doing so or point me to a tutorial that gives steps? Thx.

2021-02-16 17:56 UTC, SharonManyara requested changes
Attempting to correct the "Note" code problem.

2021-02-16 19:02 UTC, jhutchings1 commented
If you look at the diff here, you'll see that there are still changes to the menu on line 16. You should put it back like it was to avoid changing that menu. https://github.com/Klahanie/klahanie/pull/97/files

Also, @SharonManyara , it looks like you selected `request changes`. Please be aware that that choice blocks the pull request until you change your vote to `approve`. https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/about-pull-request-reviews

2021-02-16 19:15 UTC, SharonManyara approved these changes

2021-02-18 00:03 UTC, jhutchings1 approved these changes

2021-02-18 00:03 UTC, merged